class ContinentService {
  // Maps Nominatim's country names to the (differently-named) keys in
  // _countryContinents below. Not the same alias set as
  // CountryBoundariesService — that one targets countries.geo.json's
  // naming, which uses a different canonical name for several countries
  // (e.g. "united states of america" vs. this map's "us").
  static const _aliases = {
    'united states': 'us',
    'united states of america': 'us',
    'usa': 'us',
    'russia': 'russian federation',
    'czechia': 'czech republic',
    "côte d'ivoire": 'ivory coast',
    "cote d'ivoire": 'ivory coast',
    'myanmar': 'burma (myanmar)',
    'myanmar (burma)': 'burma (myanmar)',
    'north macedonia': 'macedonia',
    'eswatini': 'swaziland',
    'congo-brazzaville': 'congo',
    'congo-kinshasa': 'congo, democratic republic of',
    'dr congo': 'congo, democratic republic of',
    'democratic republic of the congo': 'congo, democratic republic of',
    'republic of the congo': 'congo',
  };

  static String? continentForCountry(String countryName) {
    final normalized = countryName.trim().toLowerCase();
    final lookupName = _aliases[normalized] ?? normalized;
    return _countryContinents[lookupName];
  }

  // Commonly cited total (193 UN member states + 2 observers). Used as the
  // denominator for a "% of the world visited" stat — an approximation
  // rather than a precise count, since "how many countries exist" has no
  // single agreed-upon answer.
  static const totalWorldCountries = 195;
}

const Map<String, String> _countryContinents = {
  'afghanistan': 'Asia',
  'albania': 'Europe',
  'algeria': 'Africa',
  'andorra': 'Europe',
  'angola': 'Africa',
  'antigua and barbuda': 'North America',
  'argentina': 'South America',
  'armenia': 'Europe',
  'australia': 'Oceania',
  'austria': 'Europe',
  'azerbaijan': 'Europe',
  'bahamas': 'North America',
  'bahrain': 'Asia',
  'bangladesh': 'Asia',
  'barbados': 'North America',
  'belarus': 'Europe',
  'belgium': 'Europe',
  'belize': 'North America',
  'benin': 'Africa',
  'bermuda': 'North America',
  'bhutan': 'Asia',
  'bolivia': 'South America',
  'bosnia and herzegovina': 'Europe',
  'botswana': 'Africa',
  'brazil': 'South America',
  'brunei': 'Asia',
  'bulgaria': 'Europe',
  'burkina': 'Africa',
  'burkina faso': 'Africa',
  'burma (myanmar)': 'Asia',
  'burundi': 'Africa',
  'cambodia': 'Asia',
  'cameroon': 'Africa',
  'canada': 'North America',
  'cape verde': 'Africa',
  'central african republic': 'Africa',
  'chad': 'Africa',
  'chile': 'South America',
  'china': 'Asia',
  'colombia': 'South America',
  'comoros': 'Africa',
  'congo': 'Africa',
  'congo, democratic republic of': 'Africa',
  'costa rica': 'North America',
  'croatia': 'Europe',
  'cuba': 'North America',
  'cyprus': 'Europe',
  'czech republic': 'Europe',
  'denmark': 'Europe',
  'djibouti': 'Africa',
  'dominica': 'North America',
  'dominican republic': 'North America',
  'east timor': 'Asia',
  'ecuador': 'South America',
  'egypt': 'Africa',
  'el salvador': 'North America',
  'equatorial guinea': 'Africa',
  'eritrea': 'Africa',
  'estonia': 'Europe',
  'ethiopia': 'Africa',
  'falkland islands': 'South America',
  'fiji': 'Oceania',
  'finland': 'Europe',
  'france': 'Europe',
  'french guiana': 'South America',
  'gabon': 'Africa',
  'gambia': 'Africa',
  'georgia': 'Europe',
  'germany': 'Europe',
  'ghana': 'Africa',
  'greece': 'Europe',
  'greenland': 'North America',
  'grenada': 'North America',
  'guatemala': 'North America',
  'guinea': 'Africa',
  'guinea bissau': 'Africa',
  'guinea-bissau': 'Africa',
  'guyana': 'South America',
  'haiti': 'North America',
  'honduras': 'North America',
  'hungary': 'Europe',
  'iceland': 'Europe',
  'india': 'Asia',
  'indonesia': 'Asia',
  'iran': 'Asia',
  'iraq': 'Asia',
  'ireland': 'Europe',
  'israel': 'Asia',
  'italy': 'Europe',
  'ivory coast': 'Africa',
  'jamaica': 'North America',
  'japan': 'Asia',
  'jordan': 'Asia',
  'kazakhstan': 'Asia',
  'kenya': 'Africa',
  'kiribati': 'Oceania',
  'korea, north': 'Asia',
  'korea, south': 'Asia',
  'kosovo': 'Europe',
  'kuwait': 'Asia',
  'kyrgyzstan': 'Asia',
  'laos': 'Asia',
  'latvia': 'Europe',
  'lebanon': 'Asia',
  'lesotho': 'Africa',
  'liberia': 'Africa',
  'libya': 'Africa',
  'liechtenstein': 'Europe',
  'lithuania': 'Europe',
  'luxembourg': 'Europe',
  'macedonia': 'Europe',
  'madagascar': 'Africa',
  'malawi': 'Africa',
  'malaysia': 'Asia',
  'maldives': 'Asia',
  'mali': 'Africa',
  'malta': 'Europe',
  'marshall islands': 'Oceania',
  'mauritania': 'Africa',
  'mauritius': 'Africa',
  'mexico': 'North America',
  'micronesia': 'Oceania',
  'moldova': 'Europe',
  'monaco': 'Europe',
  'mongolia': 'Asia',
  'montenegro': 'Europe',
  'morocco': 'Africa',
  'mozambique': 'Africa',
  'namibia': 'Africa',
  'nauru': 'Oceania',
  'nepal': 'Asia',
  'netherlands': 'Europe',
  'new caledonia': 'Oceania',
  'new zealand': 'Oceania',
  'nicaragua': 'North America',
  'niger': 'Africa',
  'nigeria': 'Africa',
  'north korea': 'Asia',
  'northern cyprus': 'Europe',
  'norway': 'Europe',
  'oman': 'Asia',
  'pakistan': 'Asia',
  'palau': 'Oceania',
  'panama': 'North America',
  'papua new guinea': 'Oceania',
  'paraguay': 'South America',
  'peru': 'South America',
  'philippines': 'Asia',
  'poland': 'Europe',
  'portugal': 'Europe',
  'puerto rico': 'North America',
  'qatar': 'Asia',
  'republic of serbia': 'Europe',
  'romania': 'Europe',
  'russian federation': 'Europe',
  'rwanda': 'Africa',
  'saint kitts and nevis': 'North America',
  'saint lucia': 'North America',
  'saint vincent and the grenadines': 'North America',
  'samoa': 'Oceania',
  'san marino': 'Europe',
  'sao tome and principe': 'Africa',
  'saudi arabia': 'Asia',
  'senegal': 'Africa',
  'serbia': 'Europe',
  'seychelles': 'Africa',
  'sierra leone': 'Africa',
  'singapore': 'Asia',
  'slovakia': 'Europe',
  'slovenia': 'Europe',
  'solomon islands': 'Oceania',
  'somalia': 'Africa',
  'somaliland': 'Africa',
  'south africa': 'Africa',
  'south korea': 'Asia',
  'south sudan': 'Africa',
  'spain': 'Europe',
  'sri lanka': 'Asia',
  'sudan': 'Africa',
  'suriname': 'South America',
  'swaziland': 'Africa',
  'sweden': 'Europe',
  'switzerland': 'Europe',
  'syria': 'Asia',
  'taiwan': 'Asia',
  'tajikistan': 'Asia',
  'tanzania': 'Africa',
  'thailand': 'Asia',
  'togo': 'Africa',
  'tonga': 'Oceania',
  'trinidad and tobago': 'North America',
  'tunisia': 'Africa',
  'turkey': 'Asia',
  'turkmenistan': 'Asia',
  'tuvalu': 'Oceania',
  'uganda': 'Africa',
  'ukraine': 'Europe',
  'united arab emirates': 'Asia',
  'united kingdom': 'Europe',
  'uruguay': 'South America',
  'us': 'North America',
  'uzbekistan': 'Asia',
  'vanuatu': 'Oceania',
  'vatican city': 'Europe',
  'venezuela': 'South America',
  'vietnam': 'Asia',
  'west bank': 'Asia',
  'western sahara': 'Africa',
  'yemen': 'Asia',
  'zambia': 'Africa',
  'zimbabwe': 'Africa',
};
